# Generated by Django 5.2.7 on 2025-10-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
