# Generated by Django 5.2.7 on 2025-10-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
